name: foody
description: My official Food Delivery App

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.1.0
  get: ^4.6.1
  google_fonts: ^2.2.0
  flutter_launcher_icons: ^0.9.2
  device_preview: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.3

flutter:
  uses-material-design: true
  
  assets:
  - assets/icon/
  - assets/splash/
  - assets/images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Medium.otf


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
