name: foody
description: My official Food Delivery App

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.1.0
  get: ^4.6.1
#  google_fonts: ^2.2.0
  flutter_launcher_icons: ^0.9.2
#  device_preview: ^1.0.0
  font_awesome_flutter: ^9.2.0
  pin_code_fields: ^7.3.0
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.0.1
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  go_router: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.1+1

flutter:
  uses-material-design: true
  
  assets:
  - assets/icon/
  - assets/splash/
  - assets/images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis-ExtraBold.otf
          weight: 800


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
