// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWiXolKAc5PmEBt2RqSjTk0LD0p1xUZCQ',
    appId: '1:1002052564261:web:6c36c2fb567c23574196cc',
    messagingSenderId: '1002052564261',
    projectId: 'foody-generic',
    authDomain: 'foody-generic.firebaseapp.com',
    storageBucket: 'foody-generic.appspot.com',
    measurementId: 'G-D6FFJM89GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaYUSP4Hyk9rVTHUFoJEQSTQ9wYf9z-AE',
    appId: '1:1002052564261:android:0db2ec51a9a742704196cc',
    messagingSenderId: '1002052564261',
    projectId: 'foody-generic',
    storageBucket: 'foody-generic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvos375yMUXhLkVz4LVgazUfen3KJJ4n0',
    appId: '1:1002052564261:ios:37f20d7a689002d44196cc',
    messagingSenderId: '1002052564261',
    projectId: 'foody-generic',
    storageBucket: 'foody-generic.appspot.com',
    iosClientId: '1002052564261-9nj3j35n86is9g23490i55tjhvhndsgu.apps.googleusercontent.com',
    iosBundleId: 'com.meyo.foody',
  );
}
